netstack -> gvisor further updates
getlantern/ipproxy pull request #18
Opened 2024-01-18 17:32 UTC by atavism

- Support running demo program on macOS
- Additional logging

2024-01-18 17:46 UTC, atavism commented
Running the demo program with these changes...

```
./demo_app -tun-gw 10.0.1.1 -tun-address 10.0.1.2
route delete default
route add default 10.0.1.2
```

I'm seeing the following in the logs:

```
DEBUG ipproxy-demo: demo.go:144 Dialing udp://208.111.40.12:3478
ERROR ipproxy: udp.go:56 Unable to dial upstream 208.111.40.12:3478: dial udp 208.111.40.12:3478: socket: too many open files [error=Unable to dial upstream %v: %v error_location=github.com/getlantern/ipproxy.(*proxy).startUDPConn.func2 (udp.go:56) error_op=dial error_text=Unable to dial upstream 208.111.40.12:3478: dial udp 208.111.40.12:3478: socket: too many open files error_type=errors.Error local_addr=208.111.40.12:3478 network=udp]
ERROR ipproxy: udp.go:56   at github.com/getlantern/ipproxy.(*proxy).startUDPConn.func2 (udp.go:56)
ERROR ipproxy: udp.go:56   at runtime.goexit (asm_arm64.s:1197)
ERROR ipproxy: udp.go:56 Caused by: dial udp 208.111.40.12:3478: socket: too many open files
ERROR ipproxy: udp.go:56 Caused by: socket: too many open files
ERROR ipproxy: udp.go:56 Caused by: too many open files
DEBUG ipproxy-demo: demo.go:144 Dialing udp://203.0.113.1:12345
ERROR ipproxy: udp.go:56 Unable to dial upstream 203.0.113.1:12345: dial udp 203.0.113.1:12345: socket: too many open files [error=Unable to dial upstream %v: %v error_location=github.com/getlantern/ipproxy.(*proxy).startUDPConn.func2 (udp.go:56) error_op=dial error_text=Unable to dial upstream 203.0.113.1:12345: dial udp 203.0.113.1:12345: socket: too many open files error_type=errors.Error local_addr=203.0.113.1:12345 network=udp]
ERROR ipproxy: udp.go:56   at github.com/getlantern/ipproxy.(*proxy).startUDPConn.func2 (udp.go:56)
ERROR ipproxy: udp.go:56   at runtime.goexit (asm_arm64.s:1197)
ERROR ipproxy: udp.go:56 Caused by: dial udp 203.0.113.1:12345: socket: too many open files
ERROR ipproxy: udp.go:56 Caused by: socket: too many open files
ERROR ipproxy: udp.go:56 Caused by: too many open files
DEBUG ipproxy-demo: demo.go:144 Dialing udp://192.73.252.134:3478
ERROR ipproxy: udp.go:56 Unable to dial upstream 192.73.252.134:3478: dial udp 192.73.252.134:3478: socket: too many open files [error=Unable to dial upstream %v: %v error_location=github.com/getlantern/ipproxy.(*proxy).startUDPConn.func2 (udp.go:56) error_op=dial error_text=Unable to dial upstream 192.73.252.134:3478: dial udp 192.73.252.134:3478: socket: too many open files error_type=errors.Error local_addr=192.73.252.134:3478 network=udp]
ERROR ipproxy: udp.go:56   at github.com/getlantern/ipproxy.(*proxy).startUDPConn.func2 (udp.go:56)
ERROR ipproxy: udp.go:56   at runtime.goexit (asm_arm64.s:1197)
ERROR ipproxy: udp.go:56 Caused by: dial udp 192.73.252.134:3478: socket: too many open files
ERROR ipproxy: udp.go:56 Caused by: socket: too many open files
ERROR ipproxy: udp.go:56 Caused by: too many open files
```

2024-01-24 16:41 UTC, reflog requested changes
this looks amazing, except for the dnsgrab dependency

2024-01-24 16:41 UTC, reflog commented on ipproxy.go
> +	DnsGrabAddress string
I'm not sure this is a good idea. Up until now ipproxy was a 'generic' project without dependency on dnsGrab.
any way to avoid this?

2024-01-24 16:48 UTC, atavism commented on ipproxy.go
> +	DnsGrabAddress string
Yeah, great point. I'll make it more generic and allow us to reroute to dnsgrab in the internalsdk instead. Will make that change!

2024-01-25 04:31 UTC, atavism commented on ipproxy.go
> +	DnsGrabAddress string
@reflog I opened a PR here with these changes https://github.com/getlantern/ipproxy/pull/19

2024-01-26 08:59 UTC, reflog approved these changes
:shipit:

2024-01-26 21:08 UTC, atavism commented
Thanks, @reflog!!

2024-01-26 21:08 UTC, merged